//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_44
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ПриходУход.
    /// </summary>
    // *** Start programmer edit section *** (ПриходУход CustomAttributes)

    // *** End programmer edit section *** (ПриходУход CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриходУходE", new string[] {
            "СправУч as \'Фио Ученика\'",
            "СправУч.Фио as \'Фио Ученика\'",
            "СправУч.Номер.Наименование as \'Номер Карты\'",
            "СправУч.КлассУч.Назв as \'Класс Ученика\'",
            "СправУч.СправРод.Фио as \'Фио Родителя\'"})]
    [View("ПриходУходL", new string[] {
            "СправУч.Фио as \'Фио Ученика\'",
            "СправУч.Номер.Наименование as \'Номер Карты\'",
            "СправУч.КлассУч.Назв as \'Класс Ученика\'",
            "СправУч.СправРод.Фио as \'Фио Родителя\'"})]
    public class ПриходУход : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Prilozhenie_44.СправУч fСправУч;
        
        // *** Start programmer edit section *** (ПриходУход CustomMembers)

        // *** End programmer edit section *** (ПриходУход CustomMembers)

        
        /// <summary>
        /// ПриходУход.
        /// </summary>
        // *** Start programmer edit section *** (ПриходУход.СправУч CustomAttributes)

        // *** End programmer edit section *** (ПриходУход.СправУч CustomAttributes)
        [PropertyStorage(new string[] {
                "СправУч"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_44.СправУч СправУч
        {
            get
            {
                // *** Start programmer edit section *** (ПриходУход.СправУч Get start)

                // *** End programmer edit section *** (ПриходУход.СправУч Get start)
                IIS.Prilozhenie_44.СправУч result = this.fСправУч;
                // *** Start programmer edit section *** (ПриходУход.СправУч Get end)

                // *** End programmer edit section *** (ПриходУход.СправУч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходУход.СправУч Set start)

                // *** End programmer edit section *** (ПриходУход.СправУч Set start)
                this.fСправУч = value;
                // *** Start programmer edit section *** (ПриходУход.СправУч Set end)

                // *** End programmer edit section *** (ПриходУход.СправУч Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриходУходE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриходУходE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриходУходE", typeof(IIS.Prilozhenie_44.ПриходУход));
                }
            }
            
            /// <summary>
            /// "ПриходУходL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриходУходL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриходУходL", typeof(IIS.Prilozhenie_44.ПриходУход));
                }
            }
        }
    }
}
